# backend/router/report_generator.py
import os
import datetime
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import json

class RouterReportGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.setup_styles()
    
    def setup_styles(self):
        """Setup custom styles for the report"""
        self.styles.add(ParagraphStyle(
            name='Title',
            parent=self.styles['Heading1'],
            fontSize=18,
            textColor=colors.darkblue,
            spaceAfter=30,
            alignment=1  # Center
        ))
        
        self.styles.add(ParagraphStyle(
            name='Heading2',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=colors.darkblue,
            spaceAfter=12
        ))
        
        self.styles.add(ParagraphStyle(
            name='VulnerabilityTitle',
            parent=self.styles['Normal'],
            fontSize=12,
            textColor=colors.red,
            spaceAfter=6
        ))
    
    def generate_pdf_report(self, scan_result: dict, filename: str = None) -> str:
        """Generate comprehensive PDF security report"""
        if not filename:
            filename = f"router_security_report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        
        # Ensure the file has .pdf extension
        if not filename.endswith('.pdf'):
            filename += '.pdf'
        
        try:
            doc = SimpleDocTemplate(filename, pagesize=letter, topMargin=0.5*inch)
            story = []
            
            # Title Section
            story.append(Paragraph("ROUTER SECURITY ASSESSMENT REPORT", self.styles['Title']))
            story.append(Spacer(1, 0.1*inch))
            story.append(Paragraph(f"Generated on: {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M:%S')}", 
                                 self.styles['Italic']))
            story.append(Spacer(1, 0.3*inch))
            
            # Router Information
            story = self._add_router_info_section(story, scan_result)
            
            # Security Summary
            story = self._add_security_summary_section(story, scan_result)
            
            # Vulnerabilities Details
            story = self._add_vulnerabilities_section(story, scan_result)
            
            # Recommendations
            story = self._add_recommendations_section(story, scan_result)
            
            # Footer
            story.append(Spacer(1, 0.5*inch))
            story.append(Paragraph("Generated by CyberX AI Security Scanner - Advanced Router Protection System", 
                                 self.styles['Italic']))
            
            doc.build(story)
            print(f"[REPORT] PDF report generated successfully: {filename}")
            return filename
            
        except Exception as e:
            print(f"[REPORT ERROR] Failed to generate PDF: {e}")
            # Fallback to JSON
            return self._generate_json_fallback(scan_result, filename.replace('.pdf', '.json'))
    
    def _add_router_info_section(self, story, scan_result):
        """Add router information section to the report"""
        story.append(Paragraph("Router Information", self.styles['Heading2']))
        
        router_info = scan_result.get('router_info', {})
        info_data = [
            ['IP Address', router_info.get('ip', 'Not detected')],
            ['Model', router_info.get('model', 'Unknown')],
            ['Firmware Version', router_info.get('firmware', 'Unknown')],
            ['Vendor', router_info.get('vendor', 'Unknown')],
            ['MAC Address', router_info.get('mac', 'Unknown')],
            ['Detected Services', ', '.join(router_info.get('services', [])) or 'None']
        ]
        
        info_table = Table(info_data, colWidths=[2*inch, 4*inch])
        info_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2E86AB')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F8F9FA')),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#DEE2E6'))
        ]))
        story.append(info_table)
        story.append(Spacer(1, 0.3*inch))
        return story
    
    def _add_security_summary_section(self, story, scan_result):
        """Add security summary section"""
        story.append(Paragraph("Security Summary", self.styles['Heading2']))
        
        vulnerabilities = scan_result.get('vulnerabilities', [])
        total_vulns = len(vulnerabilities)
        critical_vulns = len([v for v in vulnerabilities if v.get('severity') == 'critical'])
        high_vulns = len([v for v in vulnerabilities if v.get('severity') == 'high'])
        medium_vulns = len([v for v in vulnerabilities if v.get('severity') == 'medium'])
        low_vulns = len([v for v in vulnerabilities if v.get('severity') == 'low'])
        fixed_vulns = len([v for v in vulnerabilities if v.get('status') == 'fixed'])
        
        # Calculate security score
        if total_vulns > 0:
            risk_score = (critical_vulns * 4 + high_vulns * 3 + medium_vulns * 2 + low_vulns * 1)
            max_score = total_vulns * 4
            security_score = max(0, 100 - (risk_score / max_score * 100))
        else:
            security_score = 100
        
        summary_data = [
            ['Total Vulnerabilities', str(total_vulns)],
            ['Critical Issues', str(critical_vulns)],
            ['High Severity Issues', str(high_vulns)],
            ['Medium Severity Issues', str(medium_vulns)],
            ['Low Severity Issues', str(low_vulns)],
            ['Auto-Fixed Issues', str(fixed_vulns)],
            ['Security Score', f"{security_score:.1f}%"]
        ]
        
        # Color coding for severity
        colors_map = {
            'Total Vulnerabilities': colors.black,
            'Critical Issues': colors.red,
            'High Severity Issues': colors.orange,
            'Medium Severity Issues': colors.yellow,
            'Low Severity Issues': colors.green,
            'Auto-Fixed Issues': colors.blue,
            'Security Score': colors.darkgreen
        }
        
        summary_table = Table(summary_data, colWidths=[2.5*inch, 1*inch])
        table_style = [
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#6C757D')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#DEE2E6'))
        ]
        
        # Add color coding for each row
        for i, row in enumerate(summary_data):
            row_name = row[0]
            if row_name in colors_map:
                table_style.append(('TEXTCOLOR', (1, i), (1, i), colors_map[row_name]))
                table_style.append(('FONTNAME', (1, i), (1, i), 'Helvetica-Bold'))
        
        summary_table.setStyle(TableStyle(table_style))
        story.append(summary_table)
        story.append(Spacer(1, 0.3*inch))
        return story
    
    def _add_vulnerabilities_section(self, story, scan_result):
        """Add vulnerabilities details section"""
        vulnerabilities = scan_result.get('vulnerabilities', [])
        
        if vulnerabilities:
            story.append(Paragraph("Detected Vulnerabilities", self.styles['Heading2']))
            
            for i, vuln in enumerate(vulnerabilities, 1):
                # Severity color coding
                severity_colors = {
                    'critical': colors.red,
                    'high': colors.orange,
                    'medium': colors.yellow,
                    'low': colors.green
                }
                
                status_color = colors.green if vuln.get('status') == 'fixed' else colors.red
                status_text = "✅ AUTO-FIXED" if vuln.get('status') == 'fixed' else "❌ PENDING"
                fixable_text = "🛠️ AUTO-FIXABLE" if vuln.get('fixable') else "📝 MANUAL FIX REQUIRED"
                
                vuln_text = f"""
                <b>{i}. {vuln.get('title', 'Unknown Vulnerability')}</b><br/>
                <b>Severity:</b> <font color="{severity_colors.get(vuln.get('severity'), colors.black)}">{vuln.get('severity', 'unknown').upper()}</font><br/>
                <b>Status:</b> <font color="{status_color}">{status_text}</font><br/>
                <b>Fix Type:</b> {fixable_text}<br/>
                <b>Description:</b> {vuln.get('description', 'No description available')}<br/>
                """
                
                if vuln.get('evidence'):
                    vuln_text += f"<b>Evidence:</b> {vuln.get('evidence')}<br/>"
                
                if vuln.get('impact'):
                    vuln_text += f"<b>Potential Impact:</b> {vuln.get('impact')}<br/>"
                
                if vuln.get('status') != 'fixed':
                    if vuln.get('fixable'):
                        vuln_text += f"<b>Auto-Fix Applied:</b> {vuln.get('fix_method', 'Security configuration updated')}<br/>"
                    else:
                        vuln_text += f"<b>Manual Fix Required:</b> {vuln.get('recommendation', 'No specific instructions available')}<br/>"
                
                story.append(Paragraph(vuln_text, self.styles['Normal']))
                story.append(Spacer(1, 0.2*inch))
        else:
            story.append(Paragraph("🎉 No vulnerabilities detected! Your router security configuration appears to be secure.", 
                                 self.styles['Normal']))
            story.append(Spacer(1, 0.2*inch))
        
        return story
    
    def _add_recommendations_section(self, story, scan_result):
        """Add security recommendations section"""
        story.append(Paragraph("Security Recommendations", self.styles['Heading2']))
        
        vulnerabilities = scan_result.get('vulnerabilities', [])
        pending_vulns = [v for v in vulnerabilities if v.get('status') != 'fixed']
        
        if pending_vulns:
            recommendations = [
                "1. Apply all available auto-fixes immediately",
                "2. Follow manual fix instructions for non-auto-fixable issues",
                "3. Regularly update your router firmware",
                "4. Change default credentials periodically",
                "5. Disable unused services and ports",
                "6. Enable automatic security updates if available",
                "7. Monitor router logs for suspicious activity"
            ]
            
            for recommendation in recommendations:
                story.append(Paragraph(recommendation, self.styles['Normal']))
                story.append(Spacer(1, 0.1*inch))
        else:
            story.append(Paragraph("All security issues have been addressed. Maintain current security practices and monitor for new vulnerabilities.", 
                                 self.styles['Normal']))
        
        return story
    
    def _generate_json_fallback(self, scan_result: dict, filename: str) -> str:
        """Generate JSON fallback if PDF fails"""
        try:
            with open(filename, 'w') as f:
                json.dump(scan_result, f, indent=2, default=str)
            print(f"[REPORT] JSON fallback report generated: {filename}")
            return filename
        except Exception as e:
            print(f"[REPORT ERROR] JSON fallback also failed: {e}")
            return None